# Install dependencies only when needed
FROM node:16.14

# update packages
RUN apt-get update

# install tzdata
RUN apt-get install tzdata -y

# set correct timezone
ENV TZ="Europe/Kiev"

RUN rm -rf /var/www/project/public/next
RUN mkdir -p /var/www/project/public/next

WORKDIR /var/www/project/public/next

# COPY ./next/package*.json /var/www/project/public/next/

COPY ./next /var/www/project/public/next
RUN npm install --force

# RUN npm run build
EXPOSE 3000

# Run container as non-root (unprivileged) user
# The node user is provided in the Node.js Alpine base image
# USER node

ENV NODE_ENV=production
# ENV PORT=3000

# CMD [ "npm", "start" ]
CMD [ "npm", "run", "prod" ]
